spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:
            sso: ${JWK_SSO_URL:http://localhost:8081/auth/realms/IAM2/protocol/openid-connect/certs}
            internal: ${JWK_INTERNAL_URL:http://localhost:2818/api/v1.0.0/certificate/.well-known/jwks.json}

app:
  iam:
    internal-url: http://localhost:2818