server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: iam-api-docs
            uri: http://localhost:2818
            predicates:
              - Path=/iam/v3/api-docs/**
          - id: storage-api-docs
            uri: http://localhost:2819
            predicates:
              - Path=/storage/v3/api-docs/**
          - id: iam
            uri: http://localhost:2818
            predicates:
              - Path=/**
          - id: storage
            uri: http://localhost:2819
            predicates:
              - Path=/**

springdoc:
  swagger-ui:
    urls:
      - name: IAM Service
        url: http://localhost:2818/api/v1.0.0/iam/v3/api-docs
      - name: Storage Service
        url: http://localhost:2819/api/v1.0.0/storage/v3/api-docs
  api-docs:
    groups:
      enabled: true
    path: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

