app:
  version: ${APP_VERSION:1.0.0}
  baseUrl: ${APP_BASE_URL${server.servlet.context-path}:http://localhost:${server.port}${server.servlet.context-path}}

openapi:
  service:
    package: com.example.identityService.presentation.rest
    title: IAM Service 2 API document
    description: This is an official API document of IAM Service 2 service
    version: ${app.version}
    server: http://localhost:${server.port}/api/v${app.version}
    group: service

spring:
  application:
    name: iam
  config:
    import: configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  output:
    ansi:
      enabled: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
server:
  port: 2818
  servlet:
    context-path: /api/v${app.version}/
springdoc:
  swagger-ui:
    path: /api-docs

logging:
  file:
    path: logs/iam/
    name: logs/iam/application.log